#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Notch display (32px offset)
yabai -m config top_padding 22
# Normal display
# yabai -m config top_padding 54
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12

yabai -m config window_shadow off
yabai -m config window_opacity off
yabai -m config active_window_opacity 0.95
yabai -m config normal_window_opacity 0.0

yabai -m space 1 --layout stack

# Make Finder windows tileable
yabai -m rule --add app="^(Software Update|Dictionary|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

echo "yabai config loaded..."

